language: node_js
node_js:
 - "10.16"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules


script:
  - yarn build # build your site
  - yarn lint # lint app
  - ./scripts/run-lighthouse-ci.sh # run lighthouse
